<?xml version="1.0" encoding="utf-8"?><Database Name="SLIIT.ITP" Class="ITPManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ISURU-NB-IT\dev;Initial Catalog=SLIIT.ITP;Integrated Security=True" SettingsObjectName="SLIIT.Core.Properties.Settings" SettingsPropertyName="SLIIT_ITPConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_Dept" Member="TB_Depts">
    <Type Name="TB_Dept">
      <Column Name="RnDeptID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="TB_Dept_TB_HR_AttendUser" Member="TB_HR_AttendUsers" ThisKey="RnDeptID" OtherKey="Dept" Type="TB_HR_AttendUser" />
    </Type>
  </Table>
  <Table Name="dbo.TB_VF_VehicleStatus" Member="TB_VF_VehicleStatus">
    <Type Name="TB_VF_VehicleStatus">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusText" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TB_VF_VehicleStatus_TB_VF_Vehicle" Member="TB_VF_Vehicles" ThisKey="StatusID" OtherKey="Status" Type="TB_VF_Vehicle" />
    </Type>
  </Table>
  <Table Name="dbo.TB_GP_Request" Member="TB_GP_Requests">
    <Type Name="TB_GP_Request">
      <Column Name="RnRequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ReasonForRequest" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemsToBeDeclared" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VisitingArea" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateOfVisit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FromTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestComments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_HR_AttendanceLog" Member="TB_HR_AttendanceLogs">
    <Type Name="TB_HR_AttendanceLog">
      <Column Name="RnLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TB_HR_AttendUser_TB_HR_AttendanceLog" Member="TB_HR_AttendUser" ThisKey="UserID" OtherKey="RnAttendUserID" Type="TB_HR_AttendUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_HR_AttendUser" Member="TB_HR_AttendUsers">
    <Type Name="TB_HR_AttendUser">
      <Column Name="RnAttendUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Dept" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TB_HR_AttendUser_TB_HR_AttendanceLog" Member="TB_HR_AttendanceLogs" ThisKey="RnAttendUserID" OtherKey="UserID" Type="TB_HR_AttendanceLog" />
      <Association Name="TB_HR_AttendUser_TB_VF_Vehicle" Member="TB_VF_Vehicles" ThisKey="RnAttendUserID" OtherKey="DriverID" Type="TB_VF_Vehicle" />
      <Association Name="TB_Dept_TB_HR_AttendUser" Member="TB_Dept" ThisKey="Dept" OtherKey="RnDeptID" Type="TB_Dept" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_IC_Category" Member="TB_IC_Categories">
    <Type Name="TB_IC_Category">
      <Column Name="RnCatID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_IC_CustomerReturns" Member="TB_IC_CustomerReturns">
    <Type Name="TB_IC_CustomerReturn">
      <Column Name="RnReturnID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemCategory" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IssueCode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="StockQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
      <Column Name="IssueQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReturnQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IssuePrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_IC_IssueItem" Member="TB_IC_IssueItems">
    <Type Name="TB_IC_IssueItem">
      <Column Name="RnIssueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemCode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemCategory" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
      <Column Name="StockQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IssueQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IssueUnitprice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_IC_MasterData" Member="TB_IC_MasterDatas">
    <Type Name="TB_IC_MasterData">
      <Column Name="RnItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemCode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemCategory" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(16,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Menu" Member="TB_Menus">
    <Type Name="TB_Menu">
      <Column Name="RnMenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MenuImage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MenuPath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MenuColorStyle" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MenuOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_Menu_TB_MenuRole" Member="TB_MenuRoles" ThisKey="RnMenu" OtherKey="MenuID" Type="TB_MenuRole" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MenuRole" Member="TB_MenuRoles">
    <Type Name="TB_MenuRole">
      <Column Name="RnMenuRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_Menu_TB_MenuRole" Member="TB_Menu" ThisKey="MenuID" OtherKey="RnMenu" Type="TB_Menu" IsForeignKey="true" />
      <Association Name="TB_Role_TB_MenuRole" Member="TB_Role" ThisKey="RoleID" OtherKey="RnRoleID" Type="TB_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PC_IOUDetails" Member="TB_PC_IOUDetails">
    <Type Name="TB_PC_IOUDetail">
      <Column Name="RnIOUDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IOUHeaderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InsertedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TB_PC_IOUHeader_TB_PC_IOUDetail" Member="TB_PC_IOUHeader" ThisKey="IOUHeaderID" OtherKey="RnIOUID" Type="TB_PC_IOUHeader" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PC_IOUHeader" Member="TB_PC_IOUHeaders">
    <Type Name="TB_PC_IOUHeader">
      <Column Name="RnIOUID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IOUDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RejectedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RejectReason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PaidDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InsertedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InsertedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PCOfficer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TB_PC_IOUHeader_TB_PC_IOUDetail" Member="TB_PC_IOUDetails" ThisKey="RnIOUID" OtherKey="IOUHeaderID" Type="TB_PC_IOUDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Role" Member="TB_Roles">
    <Type Name="TB_Role">
      <Column Name="RnRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RoleIcon" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TB_Role_TB_MenuRole" Member="TB_MenuRoles" ThisKey="RnRoleID" OtherKey="RoleID" Type="TB_MenuRole" />
      <Association Name="TB_Role_TB_UserRole" Member="TB_UserRoles" ThisKey="RnRoleID" OtherKey="RoleID" Type="TB_UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Settings" Member="TB_Settings">
    <Type Name="TB_Setting">
      <Column Name="InstanceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmailNotificationsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SMTPServer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SMTPAuthRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SMTPUserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SMTPPassword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SMTPUseSSL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FromAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReplyToAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AllowUserRegistration" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SMTPPort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerPOPServer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MailCheckerPOPPort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerPOPLogin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MailCheckerPOPPassword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MailCheckerUseSSL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerNewIssuesCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MailCheckerAllowUnregisteredUsers" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RestrictIssueDeletion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaxAttachSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmailTemplate" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="RestrictIssueClosing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewIssuesDefaultCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowGuestSubmission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowAnonymousKBAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailSubjectTemplate" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SeeEveryonesIssues" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseDefaultSmtp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HeaderBGColor" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="MenuBarBGColor" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="LogoImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SendTechniciansEmailOnNewIssue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ServerTimeOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoursToEscalateAfter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DomainName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsADAutontication" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ADServerName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MaxDaysToClose" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_User" Member="TB_Users">
    <Type Name="TB_User">
      <Column Name="RnUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dept" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfilePic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TB_User_TB_UserRole" Member="TB_UserRoles" ThisKey="RnUserID" OtherKey="UserID" Type="TB_UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.TB_UserRole" Member="TB_UserRoles">
    <Type Name="TB_UserRole">
      <Column Name="RnUserRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_Role_TB_UserRole" Member="TB_Role" ThisKey="RoleID" OtherKey="RnRoleID" Type="TB_Role" IsForeignKey="true" />
      <Association Name="TB_User_TB_UserRole" Member="TB_User" ThisKey="UserID" OtherKey="RnUserID" Type="TB_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_VF_DailyStat" Member="TB_VF_DailyStats">
    <Type Name="TB_VF_DailyStat">
      <Column Name="RnVehicleDaily" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FromLocation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ToLocation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistanceToday" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaintenanceNotes" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VehicleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TB_VF_Vehicle_TB_VF_DailyStat" Member="TB_VF_Vehicle" ThisKey="VehicleID" OtherKey="RnVehicleID" Type="TB_VF_Vehicle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_VF_Vehicle" Member="TB_VF_Vehicles">
    <Type Name="TB_VF_Vehicle">
      <Column Name="RnVehicleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="YearOfManuf" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="YearOfPurchase" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DriverID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EngineNo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ChassisNo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TB_VF_Vehicle_TB_VF_DailyStat" Member="TB_VF_DailyStats" ThisKey="RnVehicleID" OtherKey="VehicleID" Type="TB_VF_DailyStat" />
      <Association Name="TB_HR_AttendUser_TB_VF_Vehicle" Member="TB_HR_AttendUser" ThisKey="DriverID" OtherKey="RnAttendUserID" Type="TB_HR_AttendUser" IsForeignKey="true" />
      <Association Name="TB_VF_VehicleStatus_TB_VF_Vehicle" Member="TB_VF_VehicleStatus" ThisKey="Status" OtherKey="StatusID" Type="TB_VF_VehicleStatus" IsForeignKey="true" />
    </Type>
  </Table>
</Database>